---
title: "Day 5a"
author: "Carmen"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
execute:
  warning: false
---

```{r}
#| message: false
# load packages ----
library(tidyverse)
```

### Explore the Starwars data frame using `head()`, `tail()`, and `dim()`.

```{r}
#| include: false
head(starwars, n = 20L)
tail(starwars)
dim(starwars)
summary(starwars)
```

```{r}
#| echo: false
ggplot(data = starwars, aes(x = height, y = mass, color = mass))+
  geom_point()+
  labs(x = "Height (cm)", 
       y = "Mass (kg)",
       title = "Height vs. Mass for Starwars",
       subtitle = "By Carmen Hoyt")+
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5))
```

```{r}
#| fig-cap: "Figure 1"
#| fig-alt: "Histogram"
ggplot(data = starwars, aes(x = height))+
  geom_histogram(fill = "purple", color = "orange")+
  labs(x = "Height (cm)", y = "Frequency", title = "Frequency of Height (cm) in Starwars", subtitle = "By Carmen Hoyt")+
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5))
```

## Explore summary statistics for individual columns. 

```{r}
sw_height_mean <- round(mean(starwars$height, na.rm = TRUE), digits = 3)
sw_height_sd <- round(sd(starwars$height, na.rm = TRUE), 3)
sw_mass_median <- round(median(starwars$mass, na.rm = TRUE), 3)
```

## The mean height is: `r sw_height_mean` cm, with a standard deviation of `r sw_height_sd` cm.
## The median mass is: `r sw_mass_median` kg.
